 language: cpp

 compiler: 
  - gcc
  - clang

 before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libxml2-dev qt5-default libcppunit-dev libopencv-dev 

 before_script:
   - mkdir build
   - cd build
   - cmake -C ../.travis.cache.cmake ..

 script: make

 notifications:
   email:
     - anton.deguet@jhu.edu
   on_success: change
   on_failure: always
